### ISSUE TITLE
DOES NOT WORK

### ISSUE THREAD

**Issue by WilliamEpsilon** [rom1504/MinecraftChat#5]
I opened it up, at first glance it DOES work but now it doesn't. I can type in all the fields and hit connect and it refreshes the page.

**Comment by ghost** [comment]
This is because of the lack of 1.9 support. Mineflayer and node-minecraft-protocol are currently being updated.

**Comment by Samistine** [comment]
They have been updated now. Upon trying to use this program, the web client says connection to server but nothing ever happens.

**Comment by ghost** [comment]
The software itself needs to he updated to 1.10 now. The library supports it

**Comment by PF2M** [comment]
Unrelated, but the official version of MinecraftChat at alexkvazos.com is down (he stopped the server it's hosted on), so does anyone have any mirrors or fixes? I can't get this to build properly myself.

Edit: Was able to build, now it starts but disconnects right after I hit 'Connect'. Nothing shows up in the developer console. The server is 1.8 equipped, not sure what the issue is here.

**Comment by Samistine** [comment]
I've looked through the code and don't see any API calls that would limit
it from working with 1.10

**Comment by rom1504** [comment]
Doesn't it use mineflayer ? That would be enough to make it blocked at 1.8
(for now)

**Comment by ghost** [comment]
Yes, it uses mineflayer, but it doesn't really need to...
